---
- name: AI Incident Analysis
  hosts: localhost
  gather_facts: false

  vars:
    ai_gateway_url: "http://192.168.65.3:18080/analyze"
    ai_model: "qwen3:4b"

    ai_prompt: >-
      You are an IT operations incident analyst.
      Analyze the alert and determine whether there is enough information
      to identify a probable root cause.

      If there is not enough information, return status need_more_data
      and request additional evidence using only collectors from the
      allowed_collectors list.

      Request only the minimum additional evidence needed.
      Do not request every available collector.
      Prefer 2 to 4 collectors at a time.

      If enough information exists, return status complete.
      When status is complete, you MUST provide a probable root_cause,
      confidence between 0 and 1, supporting evidence, and at least
      2 specific actionable remediation recommendations.

  tasks:

    - name: Define test alert
      ansible.builtin.set_fact:
        incident_alert:
          alertname: PaymentAPIHighErrorRate
          severity: critical
          namespace: ecommerce
          service: payment-api
          description: HTTP 500 error rate exceeded threshold
          error_rate: "76%"

    - name: Send incident to AI
      ansible.builtin.uri:
        url: "{{ ai_gateway_url }}"
        method: POST
        body_format: json
        return_content: true
        body:
          model: "{{ ai_model }}"
          prompt: "{{ ai_prompt }}"
          allowed_collectors:
            - pod_logs
            - pod_status
            - kubernetes_events
            - service_status
            - endpoints
            - network_test
          alert: "{{ incident_alert }}"
          evidence: {}
      register: ai_result

    - name: Display AI decision
      ansible.builtin.debug:
        var: ai_result.json

    - name: Initialize evidence
      ansible.builtin.set_fact:
        incident_evidence: {}

    - name: Simulate pod logs
      when: "'pod_logs' in ai_result.json.requested_data"
      ansible.builtin.set_fact:
        incident_evidence: >-
          {{
            incident_evidence |
            combine({
              'pod_logs':
              'ERROR database connection failed:
              dial tcp postgresql:5432: connection timed out. ERROR unable to process payment because database connection could not be established.'
            })
          }}

    - name: Simulate Kubernetes events
      when: "'kubernetes_events' in ai_result.json.requested_data"
      ansible.builtin.set_fact:
        incident_evidence: >-
          {{
            incident_evidence |
            combine({
              'kubernetes_events':
              'No abnormal events detected for payment-api pods. payment-api pods are Running and Ready.'
            })
          }}

    - name: Show collected evidence
      ansible.builtin.debug:
        var: incident_evidence

    - name: Send evidence back to AI
      ansible.builtin.uri:
        url: "{{ ai_gateway_url }}"
        method: POST
        body_format: json
        return_content: true
        body:
          model: "{{ ai_model }}"
          prompt: "{{ ai_prompt }}"
          allowed_collectors:
            - pod_logs
            - pod_status
            - kubernetes_events
            - service_status
            - endpoints
            - network_test
          alert: "{{ incident_alert }}"
          evidence: "{{ incident_evidence }}"
      register: second_ai_result

    - name: Show second AI decision
      ansible.builtin.debug:
        var: second_ai_result.json

    - name: Simulate network test
      when:
        - second_ai_result.json.status == "need_more_data"
        - "'network_test' in second_ai_result.json.requested_data"
      ansible.builtin.set_fact:
        incident_evidence: >-
          {{
            incident_evidence |
            combine({
              'network_test':
              'TCP connection from payment-api to postgresql:5432 failed with timeout. DNS resolution succeeds. Other network destinations are reachable.'
            })
          }}
      register: third_ai_result

    - name: Show second AI decision
      ansible.builtin.debug:
        var: third_ai_result.json
    # - name: Initialize evidence
    #   ansible.builtin.set_fact:
    #     incident_evidence: {}

    # - name: Collect pod logs
    #   when: "'pod_logs' in ai_result.json.requested_data"
    #   kubernetes.core.k8s_log:
    #     namespace: "{{ incident_alert.namespace }}"
    #     label_selectors:
    #       - "app={{ incident_alert.service }}"
    #     tail_lines: 100
    #   register: pod_logs_result

    # - name: Add pod logs to evidence
    #   when:
    #     - "'pod_logs' in ai_result.json.requested_data"
    #     - pod_logs_result is defined
    #   ansible.builtin.set_fact:
    #     incident_evidence: >-
    #       {{
    #         incident_evidence |
    #         combine({
    #           'pod_logs': pod_logs_result.log | default(pod_logs_result)
    #         })
    #       }}

    # - name: Collect Kubernetes events
    #   when: "'kubernetes_events' in ai_result.json.requested_data"
    #   kubernetes.core.k8s_info:
    #     api_version: v1
    #     kind: Event
    #     namespace: "{{ incident_alert.namespace }}"
    #   register: k8s_events_result

    # - name: Add Kubernetes events to evidence
    #   when:
    #     - "'kubernetes_events' in ai_result.json.requested_data"
    #     - k8s_events_result is defined
    #   ansible.builtin.set_fact:
    #     incident_evidence: >-
    #       {{
    #         incident_evidence |
    #         combine({
    #           'kubernetes_events': k8s_events_result.resources
    #         })
    #       }}

    # - name: Send collected evidence back to AI
    #   ansible.builtin.uri:
    #     url: "{{ ai_gateway_url }}"
    #     method: POST
    #     body_format: json
    #     return_content: true
    #     body:
    #       model: "{{ ai_model }}"
    #       prompt: "{{ ai_prompt }}"
    #       allowed_collectors:
    #         - pod_logs
    #         - pod_status
    #         - kubernetes_events
    #         - service_status
    #         - endpoints
    #         - network_test
    #       alert: "{{ incident_alert }}"
    #       evidence: "{{ incident_evidence }}"
    #   register: second_ai_result

    # - name: Display second AI decision
    #   ansible.builtin.debug:
    #     var: second_ai_result.json